### ISSUE TITLE
Use pixi.js as an alternative renderer?

### ISSUE THREAD

**Issue by sntran** [PBS-KIDS/Platypus#23]
While I'm sure CreateJS is great, pixi.js has gained attraction lately as one of the fastest renderer. Is there any plan to support it? I can help with it if I can be pointed to the right direction.

**Comment by probityrules** [comment]
Platypus v0.6.0 introduces support for pixi.js: https://github.com/PBS-KIDS/Platypus/releases/tag/v0.6.0
